apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-demo-replication
spec:
  replicas: 3
  selector:
    app: k8s-demo-pod
  template:
    metadata:
      labels:
        app: k8s-demo-pod
    spec:
      containers:
        - name: k8s-demo-container
          image: registry.localhost.com:5000/k8s/demo-api-dev
          ports:
            - containerPort: 80
            - containerPort: 443